# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Englishor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Englishor
pod 'ApiAI'
pod 'JYRadarChart'
pod 'Reusable'
pod 'CountdownLabel', '~> 4.0'
pod 'AMPopTip'
pod 'Kingfisher'
pod 'ButtonWheel'
pod 'SwiftyButton'
pod 'Floaty'
pod 'SDWebImage'
pod 'SwiftCharts'
pod 'SQLite.swift'
pod 'UITextField+Shake'
end
